import { Fragment } from "react/jsx-runtime";

function Reserve() {
    return <Fragment>
        <div class="reservation-container">
            <header class="header">
                <div class="header-content">
                    <h1 class="restaurant-name">
                        <i class="fas fa-utensils"></i> Amaravathi Authentics
                    </h1>
                    <p class="tagline">Experience Authentic South Indian Cuisine</p>
                </div>
            </header>

            <div class="main-content">
                {/* Progress Bar */}
                <div class="progress-bar">
                    <div class="progress-step active" data-step="1">
                        <div class="step-circle">
                            <i class="fas fa-calendar-alt"></i>
                        </div>
                        <span class="step-label">Date & Time</span>
                    </div>
                    <div class="progress-line"></div>
                    <div class="progress-step" data-step="2">
                        <div class="step-circle">
                            <i class="fas fa-users"></i>
                        </div>
                        <span class="step-label">Guests</span>
                    </div>
                    <div class="progress-line"></div>
                    <div class="progress-step" data-step="3">
                        <div class="step-circle">
                            <i class="fas fa-user-edit"></i>
                        </div>
                        <span class="step-label">Details</span>
                    </div>
                </div>

                <div class="content-wrapper">
                    {/* Main Reservation Form */}
                    <div class="reservation-form-wrapper">
                        {/* Step 1: Date & Time Selection */}
                        <div class="step-content active" id="step1">
                            <h2 class="step-title">
                                <i class="fas fa-calendar-check"></i> Choose Date & Time
                            </h2>

                            {/* Calendar */}
                            <div class="calendar-container">
                                <div class="calendar-header">
                                    <button class="calendar-nav" id="prevMonth">
                                        <i class="fas fa-chevron-left"></i>
                                    </button>
                                    <h3 class="calendar-month" id="currentMonth">December 2025</h3>
                                    <button class="calendar-nav" id="nextMonth">
                                        <i class="fas fa-chevron-right"></i>
                                    </button>
                                </div>
                                <div class="calendar-weekdays">
                                    <div class="weekday">Sun</div>
                                    <div class="weekday">Mon</div>
                                    <div class="weekday">Tue</div>
                                    <div class="weekday">Wed</div>
                                    <div class="weekday">Thu</div>
                                    <div class="weekday">Fri</div>
                                    <div class="weekday">Sat</div>
                                </div>
                                <div class="calendar-days" id="calendarDays">
                                    {/* Generated by JavaScript */}
                                </div>
                            </div>

                            {/* Time Slots */}
                            <div class="time-slots-container" id="timeSlotsContainer" style="display: none;">
                                <h3 class="section-subtitle">
                                    <i class="fas fa-clock"></i> Select Time Slot
                                </h3>
                                <div class="time-slots" id="timeSlots">
                                    {/* Generated by JavaScript */}
                                </div>
                            </div>

                            <button class="btn-next" id="nextToGuests" disabled>
                                Continue to Guest Selection <i class="fas fa-arrow-right"></i>
                            </button>
                        </div>

                        {/* Step 2: Guest Selection */}
                        <div class="step-content" id="step2">
                            <h2 class="step-title">
                                <i class="fas fa-user-friends"></i> Select Number of Guests
                            </h2>

                            <div class="guest-selector">
                                <button class="guest-btn" data-guests="1">
                                    <i class="fas fa-user"></i>
                                    <span>1 Guest</span>
                                    <small>Solo Dining</small>
                                </button>
                                <button class="guest-btn" data-guests="2">
                                    <i class="fas fa-user-friends"></i>
                                    <span>2 Guests</span>
                                    <small>Couple</small>
                                </button>
                                <button class="guest-btn" data-guests="3">
                                    <i class="fas fa-users"></i>
                                    <span>3 Guests</span>
                                    <small>Small Group</small>
                                </button>
                                <button class="guest-btn" data-guests="4">
                                    <i class="fas fa-users"></i>
                                    <span>4 Guests</span>
                                    <small>Family</small>
                                </button>
                                <button class="guest-btn" data-guests="5">
                                    <i class="fas fa-users"></i>
                                    <span>5 Guests</span>
                                    <small>Group</small>
                                </button>
                                <button class="guest-btn" data-guests="6">
                                    <i class="fas fa-users"></i>
                                    <span>6+ Guests</span>
                                    <small>Large Party</small>
                                </button>
                            </div>

                            {/* Table Preview */}
                            <div class="table-preview-section" id="tablePreview" style="display: none;">
                                <h3 class="section-subtitle">
                                    <i class="fas fa-chair"></i> Interactive Table Map
                                </h3>
                                <div class="table-map">
                                    <div class="map-legend">
                                        <span><i class="fas fa-circle available"></i> Available</span>
                                        <span><i class="fas fa-circle occupied"></i> Occupied</span>
                                        <span><i class="fas fa-circle selected"></i> Your Selection</span>
                                    </div>
                                    <div class="floor-plan" id="floorPlan">
                                        {/* Generated by JavaScript */}
                                    </div>
                                </div>
                            </div>

                            <div class="button-group">
                                <button class="btn-back" id="backToDate">
                                    <i class="fas fa-arrow-left"></i> Back
                                </button>
                                <button class="btn-next" id="nextToDetails" disabled>
                                    Continue to Details <i class="fas fa-arrow-right"></i>
                                </button>
                            </div>
                        </div>

                        {/* Step 3: Guest Details */}
                        <div class="step-content" id="step3">
                            <h2 class="step-title">
                                <i class="fas fa-clipboard-list"></i> Guest Information & Preferences
                            </h2>

                            <form class="guest-form" id="guestForm">
                                <div class="form-row">
                                    <div class="form-group">
                                        <label for="guestName">
                                            <i class="fas fa-user"></i> Full Name *
                                        </label>
                                        <input type="text" id="guestName" required placeholder="Enter your name" />
                                    </div>
                                    <div class="form-group">
                                        <label for="guestPhone">
                                            <i class="fas fa-phone"></i> Phone Number *
                                        </label>
                                        <input type="tel" id="guestPhone" required placeholder="+91 " pattern="[0-9]{10}" />
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="guestEmail">
                                        <i class="fas fa-envelope"></i> Email Address
                                    </label>
                                    <input type="email" id="guestEmail" placeholder="your@email.com" />
                                </div>

                                <div class="form-group">
                                    <label>
                                        <i class="fas fa-birthday-cake"></i> Occasion Type
                                    </label>
                                    <div class="occasion-selector">
                                        <button type="button" class="occasion-btn" data-occasion="regular">
                                            <i class="fas fa-utensils"></i> Regular Dining
                                        </button>
                                        <button type="button" class="occasion-btn" data-occasion="birthday">
                                            <i class="fas fa-birthday-cake"></i> Birthday
                                        </button>
                                        <button type="button" class="occasion-btn" data-occasion="anniversary">
                                            <i class="fas fa-heart"></i> Anniversary
                                        </button>
                                        <button type="button" class="occasion-btn" data-occasion="meeting">
                                            <i class="fas fa-briefcase"></i> Business Meeting
                                        </button>
                                        <button type="button" class="occasion-btn" data-occasion="devotional">
                                            <i class="fas fa-om"></i> Devotional
                                        </button>
                                        <button type="button" class="occasion-btn" data-occasion="gathering">
                                            <i class="fas fa-users"></i> Family Gathering
                                        </button>
                                    </div>
                                </div>

                                {/* Special Occasion Options */}
                                <div class="special-occasion-options" id="specialOccasionOptions" style="display: none;">
                                    {/* Generated by JavaScript based on occasion */}
                                </div>

                                <div class="form-group">
                                    <label>
                                        <i class="fas fa-chair"></i> Seating Preference
                                    </label>
                                    <div class="seating-selector">
                                        <button type="button" class="seating-btn" data-seating="indoor">
                                            <i class="fas fa-home"></i> Indoor
                                        </button>
                                        <button type="button" class="seating-btn" data-seating="outdoor">
                                            <i class="fas fa-tree"></i> Outdoor
                                        </button>
                                        <button type="button" class="seating-btn" data-seating="calm">
                                            <i class="fas fa-spa"></i> Calm Space
                                        </button>
                                        <button type="button" class="seating-btn" data-seating="family">
                                            <i class="fas fa-users"></i> Family Area
                                        </button>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="specialRequests">
                                        <i class="fas fa-comment-alt"></i> Special Requests
                                    </label>
                                    <div class="special-request-tags">
                                        <button type="button" class="request-tag" data-request="jain">Jain Food</button>
                                        <button type="button" class="request-tag" data-request="wheelchair">Wheelchair Access</button>
                                        <button type="button" class="request-tag" data-request="no-onion-garlic">No Onion/Garlic</button>
                                        <button type="button" class="request-tag" data-request="kids-menu">Kids Menu</button>
                                        <button type="button" class="request-tag" data-request="quiet">Quiet Area</button>
                                    </div>
                                    {/* rows attribute must be a number in JSX, not a string */}
                                    <textarea id="specialRequests" rows={3} placeholder="Any other special requests or dietary requirements..."></textarea>
                                </div>
                            </form>

                            <div class="button-group">
                                <button class="btn-back" id="backToGuests">
                                    <i class="fas fa-arrow-left"></i> Back
                                </button>
                                <button class="btn-submit" id="submitReservation">
                                    <i class="fas fa-check-circle"></i> Reserve Table
                                </button>
                            </div>
                        </div>

                        {/* Confirmation Screen */}
                        <div class="step-content" id="confirmation" style="display: none;">
                            <div class="confirmation-success">
                                <div class="success-icon">
                                    <i class="fas fa-check-circle"></i>
                                </div>
                                <h2 class="confirmation-title">Reservation Confirmed!</h2>
                                <p class="confirmation-message">Thank you for choosing Amaravathi Authentics</p>

                                <div class="reservation-qr">
                                    <div class="qr-code" id="qrCode">
                                        {/* QR Code generated by JavaScript */}
                                    </div>
                                    <p class="qr-instruction">Show this QR code for instant check-in</p>
                                </div>

                                <div class="reservation-details-card">
                                    <div class="detail-row">
                                        <span class="detail-label">
                                            <i class="fas fa-hashtag"></i> Reservation ID
                                        </span>
                                        <span class="detail-value" id="confirmationId">AA-2025-001</span>
                                    </div>
                                    <div class="detail-row">
                                        <span class="detail-label">
                                            <i class="fas fa-calendar"></i> Date & Time
                                        </span>
                                        <span class="detail-value" id="confirmationDateTime">Dec 15, 2025 - 7:30 PM</span>
                                    </div>
                                    <div class="detail-row">
                                        <span class="detail-label">
                                            <i class="fas fa-users"></i> Guests
                                        </span>
                                        <span class="detail-value" id="confirmationGuests">4 Guests</span>
                                    </div>
                                    <div class="detail-row">
                                        <span class="detail-label">
                                            <i class="fas fa-chair"></i> Seating
                                        </span>
                                        <span class="detail-value" id="confirmationSeating">Indoor - Table 12</span>
                                    </div>
                                    <div class="detail-row">
                                        <span class="detail-label">
                                            <i class="fas fa-user"></i> Name
                                        </span>
                                        <span class="detail-value" id="confirmationName">John Doe</span>
                                    </div>
                                </div>

                                <div class="confirmation-actions">
                                    <button class="btn-calendar">
                                        <i class="fas fa-calendar-plus"></i> Add to Calendar
                                    </button>
                                    <button class="btn-directions">
                                        <i class="fas fa-map-marker-alt"></i> Get Directions
                                    </button>
                                    <button class="btn-download">
                                        <i class="fas fa-download"></i> Download Pass
                                    </button>
                                </div>

                                <div class="recommendations">
                                    <h3>
                                        <i class="fas fa-star"></i> Today's Recommendations
                                    </h3>
                                    <div class="recommendation-cards">
                                        <div class="recommendation-card">
                                            <i class="fas fa-pepper-hot"></i>
                                            <h4>Andhra Spicy Thali</h4>
                                            <p>Chef's Special</p>
                                        </div>
                                        <div class="recommendation-card">
                                            <i class="fas fa-bread-slice"></i>
                                            <h4>Masala Dosa</h4>
                                            <p>Signature Dish</p>
                                        </div>
                                        <div class="recommendation-card">
                                            <i class="fas fa-drumstick-bite"></i>
                                            <h4>Indo-Chinese Platter</h4>
                                            <p>Must Try</p>
                                        </div>
                                    </div>
                                </div>

                                <button class="btn-new-reservation" id="newReservation">
                                    <i class="fas fa-plus"></i> Make Another Reservation
                                </button>
                            </div>
                        </div>
                    </div>

                    {/* Sticky Summary Card */}
                    <div class="summary-card" id="summaryCard">
                        <h3 class="summary-title">
                            <i class="fas fa-receipt"></i> Reservation Summary
                        </h3>
                        <div class="summary-content" id="summaryContent">
                            <div class="summary-empty">
                                <i class="fas fa-clipboard-list"></i>
                                <p>Start selecting your reservation details</p>
                            </div>
                        </div>
                        <div class="summary-footer" id="summaryFooter" style="display: none;">
                            <div class="summary-info">
                                <i class="fas fa-info-circle"></i>
                                <small>Average dining time: 60 mins</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {/* Navbar functionality script - required for mobile menu and scroll effects */}
            <script src="/static/index.js"></script>
            <script src="/static/reserve.js"></script>
        </div>
    </Fragment>
}

export default Reserve